<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        Country::truncate();


        Country::create(['name' => 'Taiwan', 'code' => 'TW', 'code3' => 'TWN', 'callcode' => '886']);
        Country::create(['name' => 'Afghanistan', 'code' => 'AF', 'code3' => 'AFG', 'callcode' => '93']);
        Country::create(['name' => 'Albania', 'code' => 'AL', 'code3' => 'ALB', 'callcode' => '355']);
        Country::create(['name' => 'Algeria', 'code' => 'DZ', 'code3' => 'DZA', 'callcode' => '213']);
        Country::create(['name' => 'American Samoa', 'code' => 'AS', 'code3' => 'ASM', 'callcode' => '1-684']);
        Country::create(['name' => 'Andorra', 'code' => 'AD', 'code3' => 'AND', 'callcode' => '376']);
        Country::create(['name' => 'Angola', 'code' => 'AO', 'code3' => 'AGO', 'callcode' => '244']);
        Country::create(['name' => 'Anguilla', 'code' => 'AI', 'code3' => 'AIA', 'callcode' => '1-264']);
        Country::create(['name' => 'Antarctica', 'code' => 'AQ', 'code3' => 'ATA', 'callcode' => '672']);
        Country::create(['name' => 'Antigua & Barbuda', 'code' => 'AG', 'code3' => 'ATG', 'callcode' => '1-268']);
        Country::create(['name' => 'Argentina', 'code' => 'AR', 'code3' => 'ARG', 'callcode' => '54']);
        Country::create(['name' => 'Armenia', 'code' => 'AM', 'code3' => 'ARM', 'callcode' => '374']);
        Country::create(['name' => 'Aruba', 'code' => 'AW', 'code3' => 'ABW', 'callcode' => '297']);
        Country::create(['name' => 'Australia', 'code' => 'AU', 'code3' => 'AUS', 'callcode' => '61']);
        Country::create(['name' => 'Austria', 'code' => 'AT', 'code3' => 'AUT', 'callcode' => '43']);
        Country::create(['name' => 'Azerbaijan', 'code' => 'AZ', 'code3' => 'AZE', 'callcode' => '994']);
        Country::create(['name' => 'Bahamas', 'code' => 'BS', 'code3' => 'BHS', 'callcode' => '1-242']);
        Country::create(['name' => 'Bahrain', 'code' => 'BH', 'code3' => 'BHR', 'callcode' => '973']);
        Country::create(['name' => 'Bangladesh', 'code' => 'BD', 'code3' => 'BGD', 'callcode' => '880']);
        Country::create(['name' => 'Barbados', 'code' => 'BB', 'code3' => 'BRB', 'callcode' => '1-246']);
        Country::create(['name' => 'Belarus', 'code' => 'BY', 'code3' => 'BLR', 'callcode' => '375']);
        Country::create(['name' => 'Belgium', 'code' => 'BE', 'code3' => 'BEL', 'callcode' => '32']);
        Country::create(['name' => 'Belize', 'code' => 'BZ', 'code3' => 'BLZ', 'callcode' => '501']);
        Country::create(['name' => 'Benin', 'code' => 'BJ', 'code3' => 'BEN', 'callcode' => '229']);
        Country::create(['name' => 'Bermuda', 'code' => 'BM', 'code3' => 'BMU', 'callcode' => '1-441']);
        Country::create(['name' => 'Bhutan', 'code' => 'BT', 'code3' => 'BTN', 'callcode' => '975']);
        Country::create(['name' => 'Bolivia', 'code' => 'BO', 'code3' => 'BOL', 'callcode' => '591']);
        Country::create(['name' => 'Caribbean Netherlands', 'code' => 'BQ', 'code3' => 'BES', 'callcode' => '599']);
        Country::create(['name' => 'Bosnia', 'code' => 'BA', 'code3' => 'BIH', 'callcode' => '387']);
        Country::create(['name' => 'Botswana', 'code' => 'BW', 'code3' => 'BWA', 'callcode' => '267']);
        Country::create(['name' => 'Bouvet Island', 'code' => 'BV', 'code3' => 'BVT', 'callcode' => '47']);
        Country::create(['name' => 'Brazil', 'code' => 'BR', 'code3' => 'BRA', 'callcode' => '55']);
        Country::create(['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'code3' => 'IOT', 'callcode' => '246']);
        Country::create(['name' => 'British Virgin Islands', 'code' => 'VG', 'code3' => 'VGB', 'callcode' => '1-284']);
        Country::create(['name' => 'Brunei', 'code' => 'BN', 'code3' => 'BRN,', 'callcode' => '673']);
        Country::create(['name' => 'Bulgaria', 'code' => 'BG', 'code3' => 'BGR', 'callcode' => '359']);
        Country::create(['name' => 'Burkina Faso', 'code' => 'BF', 'code3' => 'BFA', 'callcode' => '226']);
        Country::create(['name' => 'Burundi', 'code' => 'BI', 'code3' => 'BDI', 'callcode' => '257']);
        Country::create(['name' => 'Cape Verde', 'code' => 'CV', 'code3' => 'CPV', 'callcode' => '238']);
        Country::create(['name' => 'Cambodia', 'code' => 'KH', 'code3' => 'KHM', 'callcode' => '855']);
        Country::create(['name' => 'Cameroon', 'code' => 'CM', 'code3' => 'CMR,237']);
        Country::create(['name' => 'Canada', 'code' => 'CA', 'code3' => 'CAN', 'callcode' => '1']);
        Country::create(['name' => 'Cayman Islands', 'code' => 'KY', 'code3' => 'CYM', 'callcode' => '1-345']);
        Country::create(['name' => 'Central African Republic', 'code' => 'CF', 'code3' => 'CAF', 'callcode' => '236']);
        Country::create(['name' => 'Chad', 'code' => 'TD', 'code3' => 'TCD', 'callcode' => '235']);
        Country::create(['name' => 'Chile', 'code' => 'CL', 'code3' => 'CHL', 'callcode' => '56']);
        Country::create(['name' => 'China', 'code' => 'CN', 'code3' => 'CHN', 'callcode' => '86']);
        Country::create(['name' => 'Hong Kong', 'code' => 'HK', 'code3' => 'HKG', 'callcode' => '852']);
        Country::create(['name' => 'Macau', 'code' => 'MO', 'code3' => 'MAC', 'callcode' => '853']);
        Country::create(['name' => 'Christmas Island', 'code' => 'CX', 'code3' => 'CXR', 'callcode' => '61']);
        Country::create(['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'code3' => 'CCK', 'callcode' => '61']);
        Country::create(['name' => 'Colombia', 'code' => 'CO', 'code3' => 'COL', 'callcode' => '57']);
        Country::create(['name' => 'Comoros', 'code' => 'KM', 'code3' => 'COM', 'callcode' => '269']);
        Country::create(['name' => 'Congo - Brazzaville', 'code' => 'CG', 'code3' => 'COG', 'callcode' => '242']);
        Country::create(['name' => 'Cook Islands', 'code' => 'CK', 'code3' => 'COK', 'callcode' => '682']);
        Country::create(['name' => 'Costa Rica', 'code' => 'CR', 'code3' => 'CRI', 'callcode' => '506']);
        Country::create(['name' => 'Croatia', 'code' => 'HR', 'code3' => 'HRV', 'callcode' => '385']);
        Country::create(['name' => 'Cuba', 'code' => 'CU', 'code3' => 'CUB', 'callcode' => '53']);
        Country::create(['name' => 'Curaçao', 'code' => 'CW', 'code3' => 'CUW', 'callcode' => '599']);
        Country::create(['name' => 'Cyprus', 'code' => 'CY', 'code3' => 'CYP', 'callcode' => '357']);
        Country::create(['name' => 'Czechia', 'code' => 'CZ', 'code3' => 'CZE', 'callcode' => '420']);
        Country::create(['name' => 'Côte d’Ivoire', 'code' => 'CI', 'code3' => 'CIV', 'callcode' => '225']);
        Country::create(['name' => 'North Korea', 'code' => 'KP', 'code3' => 'PRK', 'callcode' => '850']);
        Country::create(['name' => 'Congo - Kinshasa', 'code' => 'CD', 'code3' => 'COD', 'callcode' => '243']);
        Country::create(['name' => 'Denmark', 'code' => 'DK', 'code3' => 'DNK', 'callcode' => '45']);
        Country::create(['name' => 'Djibouti', 'code' => 'DJ', 'code3' => 'DJI', 'callcode' => '253']);
        Country::create(['name' => 'Dominica', 'code' => 'DM', 'code3' => 'DMA', 'callcode' => '1-767']);
        Country::create(['name' => 'Dominican Republic', 'code' => 'DO', 'code3' => 'DOM', 'callcode' => '1-809,1-829,1-849']);
        Country::create(['name' => 'Ecuador', 'code' => 'EC', 'code3' => 'ECU', 'callcode' => '593']);
        Country::create(['name' => 'Egypt', 'code' => 'EG', 'code3' => 'EGY', 'callcode' => '20']);
        Country::create(['name' => 'El Salvador', 'code' => 'SV', 'code3' => 'SLV', 'callcode' => '503']);
        Country::create(['name' => 'Equatorial Guinea', 'code' => 'GQ', 'code3' => 'GNQ', 'callcode' => '240']);
        Country::create(['name' => 'Eritrea', 'code' => 'ER', 'code3' => 'ERI', 'callcode' => '291']);
        Country::create(['name' => 'Estonia', 'code' => 'EE', 'code3' => 'EST', 'callcode' => '372']);
        Country::create(['name' => 'Eswatini', 'code' => 'SZ', 'code3' => 'SWZ', 'callcode' => '268']);
        Country::create(['name' => 'Ethiopia', 'code' => 'ET', 'code3' => 'ETH', 'callcode' => '251']);
        Country::create(['name' => 'Falkland Islands', 'code' => 'FK', 'code3' => 'FLK', 'callcode' => '500']);
        Country::create(['name' => 'Faroe Islands', 'code' => 'FO', 'code3' => 'FRO', 'callcode' => '298']);
        Country::create(['name' => 'Fiji', 'code' => 'FJ', 'code3' => 'FJI', 'callcode' => '679']);
        Country::create(['name' => 'Finland', 'code' => 'FI', 'code3' => 'FIN', 'callcode' => '358']);
        Country::create(['name' => 'France', 'code' => 'FR', 'code3' => 'FRA', 'callcode' => '33']);
        Country::create(['name' => 'French Guiana', 'code' => 'GF', 'code3' => 'GUF', 'callcode' => '594']);
        Country::create(['name' => 'French Polynesia', 'code' => 'PF', 'code3' => 'PYF', 'callcode' => '689']);
        Country::create(['name' => 'French Southern Territories', 'code' => 'TF', 'code3' => 'ATF', 'callcode' => '262']);
        Country::create(['name' => 'Gabon', 'code' => 'GA', 'code3' => 'GAB', 'callcode' => '241']);
        Country::create(['name' => 'Gambia', 'code' => 'GM', 'code3' => 'GMB', 'callcode' => '220']);
        Country::create(['name' => 'Georgia', 'code' => 'GE', 'code3' => 'GEO', 'callcode' => '995']);
        Country::create(['name' => 'Germany', 'code' => 'DE', 'code3' => 'DEU', 'callcode' => '49']);
        Country::create(['name' => 'Ghana', 'code' => 'GH', 'code3' => 'GHA', 'callcode' => '233']);
        Country::create(['name' => 'Gibraltar', 'code' => 'GI', 'code3' => 'GIB', 'callcode' => '350']);
        Country::create(['name' => 'Greece', 'code' => 'GR', 'code3' => 'GRC', 'callcode' => '30']);
        Country::create(['name' => 'Greenland', 'code' => 'GL', 'code3' => 'GRL', 'callcode' => '299']);
        Country::create(['name' => 'Grenada', 'code' => 'GD', 'code3' => 'GRD,1-473']);
        Country::create(['name' => 'Guadeloupe', 'code' => 'GP', 'code3' => 'GLP', 'callcode' => '590']);
        Country::create(['name' => 'Guam', 'code' => 'GU', 'code3' => 'GUM', 'callcode' => '1-671']);
        Country::create(['name' => 'Guatemala', 'code' => 'GT', 'code3' => 'GTM', 'callcode' => '502']);
        Country::create(['name' => 'Guernsey,', 'code' => 'GG', 'code3' => 'GGY', 'callcode' => '44']);
        Country::create(['name' => 'Guinea', 'code' => 'GN', 'code3' => 'GIN', 'callcode' => '224']);
        Country::create(['name' => 'Guinea-Bissau', 'code' => 'GW', 'code3' => 'GNB', 'callcode' => '245']);
        Country::create(['name' => 'Guyana', 'code' => 'GY', 'code3' => 'GUY', 'callcode' => '592']);
        Country::create(['name' => 'Haiti', 'code' => 'HT', 'code3' => 'HTI', 'callcode' => '509']);
        Country::create(['name' => 'Heard & McDonald Islands', 'code' => 'HM', 'code3' => 'HMD', 'callcode' => '672']);
        Country::create(['name' => 'Vatican City', 'code' => 'VA', 'code3' => 'VAT', 'callcode' => '39-06']);
        Country::create(['name' => 'Honduras', 'code' => 'HN', 'code3' => 'HND', 'callcode' => '504']);
        Country::create(['name' => 'Hungary', 'code' => 'HU', 'code3' => 'HUN', 'callcode' => '36']);
        Country::create(['name' => 'Iceland', 'code' => 'IS', 'code3' => 'ISL', 'callcode' => '354']);
        Country::create(['name' => 'India', 'code' => 'IN', 'code3' => 'IND', 'callcode' => '91']);
        Country::create(['name' => 'Indonesia', 'code' => 'ID', 'code3' => 'IDN', 'callcode' => '62']);
        Country::create(['name' => 'Iran', 'code' => 'IR', 'code3' => 'IRN', 'callcode' => '98']);
        Country::create(['name' => 'Iraq', 'code' => 'IQ', 'code3' => 'IRQ', 'callcode' => '964']);
        Country::create(['name' => 'Ireland', 'code' => 'IE', 'code3' => 'IRL', 'callcode' => '353']);
        Country::create(['name' => 'Isle of Man', 'code' => 'IM', 'code3' => 'IMN', 'callcode' => '44']);
        Country::create(['name' => 'Israel', 'code' => 'IL', 'code3' => 'ISR,', 'callcode' => '972']);
        Country::create(['name' => 'Italy', 'code' => 'IT', 'code3' => 'ITA', 'callcode' => '39']);
        Country::create(['name' => 'Jamaica', 'code' => 'JM', 'code3' => 'JAM', 'callcode' => '1-876']);
        Country::create(['name' => 'Japan', 'code' => 'JP', 'code3' => 'JPN', 'callcode' => '81']);
        Country::create(['name' => 'Jersey', 'code' => 'JE', 'code3' => 'JEY', 'callcode' => '44']);
        Country::create(['name' => 'Jordan', 'code' => 'JO', 'code3' => 'JOR', 'callcode' => '962']);
        Country::create(['name' => 'Kazakhstan', 'code' => 'KZ', 'code3' => 'KAZ', 'callcode' => '7']);
        Country::create(['name' => 'Kenya', 'code' => 'KE', 'code3' => 'KEN', 'callcode' => '254']);
        Country::create(['name' => 'Kiribati', 'code' => 'KI', 'code3' => 'KIR', 'callcode' => '686']);
        Country::create(['name' => 'Kuwait', 'code' => 'KW', 'code3' => 'KWT', 'callcode' => '965']);
        Country::create(['name' => 'Kyrgyzstan', 'code' => 'KG', 'code3' => 'KGZ', 'callcode' => '996']);
        Country::create(['name' => 'Laos', 'code' => 'LA', 'code3' => 'LAO', 'callcode' => '856']);
        Country::create(['name' => 'Latvia', 'code' => 'LV', 'code3' => 'LVA', 'callcode' => '371']);
        Country::create(['name' => 'Lebanon', 'code' => 'LB', 'code3' => 'LBN', 'callcode' => '961']);
        Country::create(['name' => 'Lesotho', 'code' => 'LS', 'code3' => 'LSO', 'callcode' => '266']);
        Country::create(['name' => 'Liberia', 'code' => 'LR', 'code3' => 'LBR', 'callcode' => '231']);
        Country::create(['name' => 'Libya', 'code' => 'LY', 'code3' => 'LBY', 'callcode' => '218']);
        Country::create(['name' => 'Liechtenstein', 'code' => 'LI', 'code3' => 'LIE', 'callcode' => '423']);
        Country::create(['name' => 'Lithuania', 'code' => 'LT', 'code3' => 'LTU', 'callcode' => '370']);
        Country::create(['name' => 'Luxembourg', 'code' => 'LU', 'code3' => 'LUX', 'callcode' => '352']);
        Country::create(['name' => 'Madagascar', 'code' => 'MG', 'code3' => 'MDG', 'callcode' => '261']);
        Country::create(['name' => 'Malawi', 'code' => 'MW', 'code3' => 'MWI', 'callcode' => '265']);
        Country::create(['name' => 'Malaysia', 'code' => 'MY', 'code3' => 'MYS', 'callcode' => '60']);
        Country::create(['name' => 'Maldives', 'code' => 'MV', 'code3' => 'MDV', 'callcode' => '960']);
        Country::create(['name' => 'Mali', 'code' => 'ML', 'code3' => 'MLI', 'callcode' => '223']);
        Country::create(['name' => 'Malta', 'code' => 'MT', 'code3' => 'MLT', 'callcode' => '356']);
        Country::create(['name' => 'Marshall Islands', 'code' => 'MH', 'code3' => 'MHL', 'callcode' => '692']);
        Country::create(['name' => 'Martinique', 'code' => 'MQ', 'code3' => 'MTQ', 'callcode' => '596']);
        Country::create(['name' => 'Mauritania', 'code' => 'MR', 'code3' => 'MRT', 'callcode' => '222']);
        Country::create(['name' => 'Mauritius', 'code' => 'MU', 'code3' => 'MUS', 'callcode' => '230']);
        Country::create(['name' => 'Mayotte', 'code' => 'YT', 'code3' => 'MYT', 'callcode' => '262']);
        Country::create(['name' => 'Mexico', 'code' => 'MX', 'code3' => 'MEX', 'callcode' => '52']);
        Country::create(['name' => 'Micronesia', 'code' => 'FM', 'code3' => 'FSM', 'callcode' => '691']);
        Country::create(['name' => 'Monaco', 'code' => 'MC', 'code3' => 'MCO', 'callcode' => '377']);
        Country::create(['name' => 'Mongolia', 'code' => 'MN', 'code3' => 'MNG', 'callcode' => '976']);
        Country::create(['name' => 'Montenegro', 'code' => 'ME', 'code3' => 'MNE', 'callcode' => '382']);
        Country::create(['name' => 'Montserrat', 'code' => 'MS', 'code3' => 'MSR', 'callcode' => '1-664']);
        Country::create(['name' => 'Morocco', 'code' => 'MA', 'code3' => 'MAR', 'callcode' => '212']);
        Country::create(['name' => 'Mozambique', 'code' => 'MZ', 'code3' => 'MOZ', 'callcode' => '258']);
        Country::create(['name' => 'Myanmar', 'code' => 'MM', 'code3' => 'MMR', 'callcode' => '95']);
        Country::create(['name' => 'Namibia', 'code' => 'NA', 'code3' => 'NAM', 'callcode' => '264']);
        Country::create(['name' => 'Nauru', 'code' => 'NR', 'code3' => 'NRU', 'callcode' => '674']);
        Country::create(['name' => 'Nepal', 'code' => 'NP', 'code3' => 'NPL', 'callcode' => '977']);
        Country::create(['name' => 'Netherlands', 'code' => 'NL', 'code3' => 'NLD', 'callcode' => '31']);
        Country::create(['name' => 'New Caledonia', 'code' => 'NC', 'code3' => 'NCL', 'callcode' => '687']);
        Country::create(['name' => 'New Zealand', 'code' => 'NZ', 'code3' => 'NZL', 'callcode' => '64']);
        Country::create(['name' => 'Nicaragua', 'code' => 'NI', 'code3' => 'NIC', 'callcode' => '505']);
        Country::create(['name' => 'Niger', 'code' => 'NE', 'code3' => 'NER', 'callcode' => '227']);
        Country::create(['name' => 'Nigeria', 'code' => 'NG', 'code3' => 'NGA', 'callcode' => '234']);
        Country::create(['name' => 'Niue', 'code' => 'NU', 'code3' => 'NIU', 'callcode' => '683']);
        Country::create(['name' => 'Norfolk Island', 'code' => 'NF', 'code3' => 'NFK', 'callcode' => '672']);
        Country::create(['name' => 'Northern Mariana Islands', 'code' => 'MP', 'code3' => 'MNP', 'callcode' => '1-670']);
        Country::create(['name' => 'Norway', 'code' => 'NO', 'code3' => 'NOR', 'callcode' => '47']);
        Country::create(['name' => 'Oman', 'code' => 'OM', 'code3' => 'OMN', 'callcode' => '968']);
        Country::create(['name' => 'Pakistan', 'code' => 'PK', 'code3' => 'PAK', 'callcode' => '92']);
        Country::create(['name' => 'Palau', 'code' => 'PW', 'code3' => 'PLW', 'callcode' => '680']);
        Country::create(['name' => 'Panama', 'code' => 'PA', 'code3' => 'PAN', 'callcode' => '507']);
        Country::create(['name' => 'Papua New Guinea', 'code' => 'PG', 'code3' => 'PNG', 'callcode' => '675']);
        Country::create(['name' => 'Paraguay', 'code' => 'PY', 'code3' => 'PRY', 'callcode' => '595']);
        Country::create(['name' => 'Peru', 'code' => 'PE', 'code3' => 'PER', 'callcode' => '51']);
        Country::create(['name' => 'Philippines', 'code' => 'PH', 'code3' => 'PHL', 'callcode' => '63']);
        Country::create(['name' => 'Pitcairn Islands', 'code' => 'PN', 'code3' => 'PCN', 'callcode' => '870']);
        Country::create(['name' => 'Poland', 'code' => 'PL', 'code3' => 'POL', 'callcode' => '48']);
        Country::create(['name' => 'Portugal', 'code' => 'PT', 'code3' => 'PRT', 'callcode' => '351']);
        Country::create(['name' => 'Puerto Rico', 'code' => 'PR', 'code3' => 'PRI', 'callcode' => '1']);
        Country::create(['name' => 'Qatar', 'code' => 'QA', 'code3' => 'QAT', 'callcode' => '974']);
        Country::create(['name' => 'South Korea', 'code' => 'KR', 'code3' => 'KOR', 'callcode' => '82']);
        Country::create(['name' => 'Moldova', 'code' => 'MD', 'code3' => 'MDA', 'callcode' => '373']);
        Country::create(['name' => 'Romania', 'code' => 'RO', 'code3' => 'ROU', 'callcode' => '40']);
        Country::create(['name' => 'Russia', 'code' => 'RU', 'code3' => 'RUS', 'callcode' => '7']);
        Country::create(['name' => 'Rwanda', 'code' => 'RW', 'code3' => 'RWA', 'callcode' => '250']);
        Country::create(['name' => 'Réunion', 'code' => 'RE', 'code3' => 'REU', 'callcode' => '262']);
        Country::create(['name' => 'St. Barthélemy', 'code' => 'BL', 'code3' => 'BLM', 'callcode' => '590']);
        Country::create(['name' => 'St. Helena', 'code' => 'SH', 'code3' => 'SHN', 'callcode' => '290']);
        Country::create(['name' => 'St. Kitts & Nevis', 'code' => 'KN', 'code3' => 'KNA', 'callcode' => '1-869']);
        Country::create(['name' => 'St. Lucia', 'code' => 'LC', 'code3' => 'LCA', 'callcode' => '1-758']);
        Country::create(['name' => 'St. Martin', 'code' => 'MF', 'code3' => 'MAF', 'callcode' => '590']);
        Country::create(['name' => 'St. Pierre & Miquelon', 'code' => 'PM', 'code3' => 'SPM', 'callcode' => '508']);
        Country::create(['name' => 'St. Vincent & Grenadines', 'code' => 'VC', 'code3' => 'VCT', 'callcode' => '1-784']);
        Country::create(['name' => 'Samoa', 'code' => 'WS', 'code3' => 'WSM', 'callcode' => '685']);
        Country::create(['name' => 'San Marino', 'code' => 'SM', 'code3' => 'SMR', 'callcode' => '378']);
        Country::create(['name' => 'São Tomé & Príncipe', 'code' => 'ST', 'code3' => 'STP', 'callcode' => '239']);
        Country::create(['name' => 'Saudi Arabia', 'code' => 'SA', 'code3' => 'SAU', 'callcode' => '966']);
        Country::create(['name' => 'Senegal,', 'code' => 'SN', 'code3' => 'SEN', 'callcode' => '221']);
        Country::create(['name' => 'Serbia', 'code' => 'RS', 'code3' => 'SRB', 'callcode' => '381']);
        Country::create(['name' => 'Seychelles', 'code' => 'SC', 'code3' => 'SYC', 'callcode' => '248']);
        Country::create(['name' => 'Sierra Leone', 'code' => 'SL', 'code3' => 'SLE', 'callcode' => '232']);
        Country::create(['name' => 'Singapore', 'code' => 'SG', 'code3' => 'SGP', 'callcode' => '65']);
        Country::create(['name' => 'Sint Maarten', 'code' => 'SX', 'code3' => 'SXM', 'callcode' => '1-721']);
        Country::create(['name' => 'Slovakia', 'code' => 'SK', 'code3' => 'SVK', 'callcode' => '421']);
        Country::create(['name' => 'Slovenia', 'code' => 'SI', 'code3' => 'SVN', 'callcode' => '386']);
        Country::create(['name' => 'Solomon Islands', 'code' => 'SB', 'code3' => 'SLB', 'callcode' => '677']);
        Country::create(['name' => 'Somalia', 'code' => 'SO', 'code3' => 'SOM,=', 'callcode' => '252']);
        Country::create(['name' => 'South Africa', 'code' => 'ZA', 'code3' => 'ZAF', 'callcode' => '27']);
        Country::create(['name' => 'South Georgia & South Sandwich Islands', 'code' => 'GS', 'code3' => 'SGS', 'callcode' => '500']);
        Country::create(['name' => 'South Sudan', 'code' => 'SS', 'code3' => 'SSD', 'callcode' => '211']);
        Country::create(['name' => 'Spain', 'code' => 'ES', 'code3' => 'ESP', 'callcode' => '34']);
        Country::create(['name' => 'Sri Lanka', 'code' => 'LK', 'code3' => 'LKA', 'callcode' => '94']);
        Country::create(['name' => 'Palestine', 'code' => 'PS', 'code3' => 'PSE', 'callcode' => '970']);
        Country::create(['name' => 'Sudan', 'code' => 'SD', 'code3' => 'SDN', 'callcode' => '249']);
        Country::create(['name' => 'Suriname', 'code' => 'SR', 'code3' => 'SUR', 'callcode' => '597']);
        Country::create(['name' => 'Svalbard & Jan Mayen', 'code' => 'SJ', 'code3' => 'SJM', 'callcode' => '47']);
        Country::create(['name' => 'Sweden', 'code' => 'SE', 'code3' => 'SWE', 'callcode' => '46']);
        Country::create(['name' => 'Switzerland', 'code' => 'CH', 'code3' => 'CHE', 'callcode' => '41']);
        Country::create(['name' => 'Syria', 'code' => 'SY', 'code3' => 'SYR', 'callcode' => '963']);
        Country::create(['name' => 'Tajikistan', 'code' => 'TJ', 'code3' => 'TJK', 'callcode' => '992']);
        Country::create(['name' => 'Thailand', 'code' => 'TH', 'code3' => 'THA', 'callcode' => '66']);
        Country::create(['name' => 'North Macedonia', 'code' => 'MK', 'code3' => 'MKD', 'callcode' => '389']);
        Country::create(['name' => 'Timor-Leste', 'code' => 'TL', 'code3' => 'TLS', 'callcode' => '670']);
        Country::create(['name' => 'Togo', 'code' => 'TG', 'code3' => 'TGO', 'callcode' => '228']);
        Country::create(['name' => 'Tokelau', 'code' => 'TK', 'code3' => 'TKL', 'callcode' => '690']);
        Country::create(['name' => 'Tonga', 'code' => 'TO', 'code3' => 'TON', 'callcode' => '676']);
        Country::create(['name' => 'Trinidad & Tobago', 'code' => 'TT', 'code3' => 'TTO', 'callcode' => '1-868']);
        Country::create(['name' => 'Tunisia', 'code' => 'TN', 'code3' => 'TUN', 'callcode' => '216']);
        Country::create(['name' => 'Turkey', 'code' => 'TR', 'code3' => 'TUR', 'callcode' => '90']);
        Country::create(['name' => 'Turkmenistan', 'code' => 'TM', 'code3' => 'TKM', 'callcode' => '993']);
        Country::create(['name' => 'Turks & Caicos Islands', 'code' => 'TC', 'code3' => 'TCA', 'callcode' => '1-649']);
        Country::create(['name' => 'Tuvalu', 'code' => 'TV', 'code3' => 'TUV', 'callcode' => '688']);
        Country::create(['name' => 'Uganda', 'code' => 'UG', 'code3' => 'UGA', 'callcode' => '256']);
        Country::create(['name' => 'Ukraine', 'code' => 'UA', 'code3' => 'UKR', 'callcode' => '380']);
        Country::create(['name' => 'United Arab Emirates', 'code' => 'AE', 'code3' => 'ARE', 'callcode' => '971']);
        Country::create(['name' => 'UK', 'code' => 'GB', 'code3' => 'GBR', 'callcode' => '44']);
        Country::create(['name' => 'Tanzania', 'code' => 'TZ', 'code3' => 'TZA', 'callcode' => '255']);
        Country::create(['name' => 'U.S. Outlying Islands', 'code' => 'UM', 'code3' => 'UMI', 'callcode' => '']);
        Country::create(['name' => 'U.S. Virgin Islands', 'code' => 'VI', 'code3' => 'VIR', 'callcode' => '1-340']);
        Country::create(['name' => 'US', 'code' => 'US', 'code3' => 'USA', 'callcode' => '1']);
        Country::create(['name' => 'Uruguay', 'code' => 'UY', 'code3' => 'URY', 'callcode' => '598']);
        Country::create(['name' => 'Uzbekistan', 'code' => 'UZ', 'code3' => 'UZB', 'callcode' => '998']);
        Country::create(['name' => 'Vanuatu', 'code' => 'VU', 'code3' => 'VUT', 'callcode' => '678']);
        Country::create(['name' => 'Venezuela', 'code' => 'VE', 'code3' => 'VEN', 'callcode' => '58']);
        Country::create(['name' => 'Vietnam', 'code' => 'VN', 'code3' => 'VNM', 'callcode' => '84']);
        Country::create(['name' => 'Wallis & Futuna', 'code' => 'WF', 'code3' => 'WLF', 'callcode' => '681']);
        Country::create(['name' => 'Western Sahara', 'code' => 'EH', 'code3' => 'ESH', 'callcode' => '212']);
        Country::create(['name' => 'Yemen', 'code' => 'YE', 'code3' => 'YEM', 'callcode' => '967']);
        Country::create(['name' => 'Zambia', 'code' => 'ZM', 'code3' => 'ZMB', 'callcode' => '260']);
        Country::create(['name' => 'Zimbabwe', 'code' => 'ZW', 'code3' => 'ZWE', 'callcode' => '263']);
        Country::create(['name' => 'Åland Islands', 'code' => 'AX', 'code3' => 'ALA', 'callcode' => '358']);
           
    }
}
